# Generated by Django 5.2.16 on 2026-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_page_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='wp_post_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Original WordPress post ID, for migration traceability. Null for pages not sourced from the WordPress import.', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='wp_post_id',
            field=models.PositiveIntegerField(blank=True, help_text='Original WordPress post ID, for migration traceability. Null for pages not sourced from the WordPress import.', null=True, unique=True),
        ),
    ]
