"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Search, TriangleAlert } from "lucide-react";
import type { ReviewSummary } from "@/components/CourseReviewPanel";

export type CourseListItem = { id:number; title:string; slug:string; status:"draft"|"published"|"archived"; category_name:string; program_type_name:string; image:string|null; image_alt:string; is_active:boolean; needs_content_review:boolean; needs_url_review:boolean; seo_complete:boolean; review_summary:ReviewSummary };

export function CoursesTable({courses}:{courses:CourseListItem[]}) {
 const [query,setQuery]=useState(""),[queue,setQueue]=useState("all");
 const rows=useMemo(()=>courses.filter(c=>{const q=query.toLowerCase();const matches=!q||c.title.toLowerCase().includes(q)||c.slug.includes(q);const s=c.review_summary;const inQueue=queue==="all"||(queue==="content"&&s.content_review.status!=="clear")||(queue==="url"&&s.url_review.status!=="clear")||(queue==="seo"&&s.seo.status!=="complete")||(queue==="ready"&&s.publication.status==="ready");return matches&&inQueue}),[courses,query,queue]);
 return <div><div className="mb-4 flex flex-wrap gap-3"><label className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2"><Search className="h-4 w-4"/><input className="bg-transparent text-sm outline-none" placeholder="Search courses…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-sm font-semibold"><TriangleAlert className="h-4 w-4 text-gold"/><select value={queue} onChange={e=>setQueue(e.target.value)} className="bg-transparent outline-none"><option value="all">All review states</option><option value="content">Content review</option><option value="url">URL / ownership review</option><option value="seo">Missing SEO</option><option value="ready">Ready to publish</option></select></label><span className="self-center text-sm text-text-body">{rows.length} of {courses.length}</span></div><div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-bg-light text-xs uppercase text-text-body"><tr><th className="p-3">Course</th><th className="p-3">Content Review</th><th className="p-3">URL Review</th><th className="p-3">SEO</th><th className="p-3">Media</th><th className="p-3">Publication</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} className="border-t border-border transition-colors hover:bg-bg-light/60"><td className="p-3"><Link className="font-bold text-navy hover:text-cta" href={`/courses/${c.slug}`}>{c.title}</Link><div className="text-xs text-text-body">{c.slug}</div><div className="text-[11px] text-text-body">{c.category_name} · {c.program_type_name}</div></td><SummaryCell item={c.review_summary.content_review}/><SummaryCell item={c.review_summary.url_review}/><SummaryCell item={c.review_summary.seo}/><SummaryCell item={c.review_summary.media}/><SummaryCell item={c.review_summary.publication}/></tr>)}</tbody></table></div></div>;
}

function SummaryCell({item}:{item:{status:string;open_count?:number;deferred_count?:number;blocking_count?:number}}){const good=["clear","complete","ready","published"].includes(item.status);const count=item.open_count||item.deferred_count||item.blocking_count;return <td className="p-3"><span className={`whitespace-nowrap rounded-full px-2 py-1 text-xs font-bold capitalize ${good?"bg-emerald/10 text-emerald":"bg-gold/15 text-gold"}`}>{item.status}{count?` · ${count}`:""}</span></td>}
