"use client";

import { useState } from "react";
import { CheckCircle2, CircleAlert, Loader2 } from "lucide-react";

export type ReviewIssue = { id:number; category:"encoding"|"scraped_navigation"|"url"|"seo"|"ownership"; category_label:string; field_name:string; summary:string; details:Record<string,unknown>; blocking:boolean; status:"open"|"reviewed"|"corrected"; resolution_note:string; reviewed_by_name?:string|null; reviewed_at?:string|null };
export type ReviewSummary = Record<"content_review"|"url_review"|"seo"|"media"|"publication",{status:string;open_count?:number;deferred_count?:number;blocking_count?:number;complete?:boolean}>;
const ORDER:ReviewIssue["category"][]=["encoding","scraped_navigation","url","seo","ownership"];
const LABELS:Record<ReviewIssue["category"],string>={encoding:"Encoding issues",scraped_navigation:"Scraped-navigation contamination",url:"Canonical / slug conflicts",seo:"Missing SEO metadata",ownership:"Landing-page ownership conflicts"};

export function CourseReviewPanel({issues,summary}:{issues:ReviewIssue[];summary:ReviewSummary}) {
 return <section className="space-y-4 rounded-2xl border border-border bg-card p-5"><div><h2 className="text-lg font-bold text-navy">Course review</h2><p className="text-sm text-text-body">Review decisions are audited separately; source payload and hash are never rewritten.</p></div><div className="grid gap-2 sm:grid-cols-5">{Object.entries(summary).map(([key,value])=><div key={key} className="rounded-xl border border-border bg-bg-light p-3"><div className="text-[10px] font-bold uppercase text-text-body">{key.replaceAll("_"," ")}</div><div className={`mt-1 text-sm font-bold ${["clear","complete","ready","published"].includes(value.status)?"text-emerald":"text-gold"}`}>{value.status} {value.open_count?`(${value.open_count})`:value.deferred_count?`(${value.deferred_count})`:value.blocking_count?`(${value.blocking_count})`:""}</div></div>)}</div>{ORDER.map(category=>{const rows=issues.filter(issue=>issue.category===category);if(!rows.length)return null;return <div key={category}><h3 className="mb-2 text-sm font-extrabold text-navy">{LABELS[category]}</h3><div className="space-y-2">{rows.map(issue=><IssueRow key={issue.id} issue={issue}/>)}</div></div>})}</section>;
}

function IssueRow({issue}:{issue:ReviewIssue}) {
 const [note,setNote]=useState(issue.resolution_note||""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function resolve(status:"reviewed"|"corrected"){setSaving(true);setError("");const res=await fetch(`/api/proxy/course-review-issues/${issue.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,resolution_note:note})});if(res.ok)window.location.reload();else{const data=await res.json().catch(()=>({}));setError(String(data.status||data.detail||"Update failed"));setSaving(false)}}
 const d=issue.details||{};
 return <div className={`rounded-xl border p-3 ${issue.status==="open"?"border-gold/40 bg-gold/5":"border-emerald/30 bg-emerald/5"}`}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-bold text-navy">{issue.status==="open"?<CircleAlert className="h-4 w-4 text-gold"/>:<CheckCircle2 className="h-4 w-4 text-emerald"/>}{issue.summary}</div><div className="mt-1 text-xs text-text-body">Field: <b>{issue.field_name||"course"}</b> · {issue.blocking?"Blocks publication":"Advisory"}</div></div><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold uppercase">{issue.status}</span></div>{Array.isArray(d.values)&&<div className="mt-2 text-xs text-destructive">Detected: {(d.values as string[]).join(" · ")}</div>}{typeof d.current_primary_slug==="string"&&<div className="mt-2 grid gap-1 text-xs text-text-body"><div>Current primary slug: <b>{d.current_primary_slug}</b></div><div>Imported canonical URL: <b>{String(d.imported_canonical_url||"")}</b></div><div>Proposed action: {String(d.proposed_action||"")}</div></div>}{typeof d.page_slug==="string"&&<div className="mt-2 grid gap-1 text-xs text-text-body"><div>Conflicting page: <b>/{d.page_slug}</b> ({String(d.page_status)})</div><div>{String(d.proposed_action||"")}</div></div>}{Array.isArray(d.missing_fields)&&<div className="mt-2 text-xs text-text-body">Missing: {(d.missing_fields as string[]).join(", ")}</div>}{issue.status==="open"&&<div className="mt-3 flex flex-wrap items-center gap-2"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Review note (optional)" className="min-w-64 flex-1 rounded-lg border border-border px-3 py-2 text-xs"/><button disabled={saving} onClick={()=>resolve("reviewed")} className="rounded-lg border border-emerald/40 px-3 py-2 text-xs font-bold text-emerald">Mark reviewed</button><button disabled={saving} onClick={()=>resolve("corrected")} className="rounded-lg bg-emerald px-3 py-2 text-xs font-bold text-white">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:"Mark corrected"}</button>{error&&<span className="text-xs text-destructive">{error}</span>}</div>}</div>;
}
