# Generated by Django 5.2.16 on 2026-08-04 11:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('pages', '0002_seed_page_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialitem',
            name='label',
        ),
        migrations.RemoveField(
            model_name='historicaltestimonial',
            name='role_company',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role_company',
        ),
        migrations.AddField(
            model_name='banner',
            name='badge_icon',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='award', max_length=32),
        ),
        migrations.AddField(
            model_name='banner',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='bottom_card_icon',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='users-round', max_length=32),
        ),
        migrations.AddField(
            model_name='banner',
            name='bottom_card_subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='bottom_card_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='centres_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='floating_stat_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='floating_stat_value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_cta_external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_cta_internal_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page'),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_cta_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='top_card_icon',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='graduation-cap', max_length=32),
        ),
        migrations.AddField(
            model_name='banner',
            name='top_card_subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='top_card_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='credentialitem',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cta',
            name='secondary_cta_external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cta',
            name='secondary_cta_internal_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page'),
        ),
        migrations.AddField(
            model_name='cta',
            name='secondary_cta_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='badge_icon',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='award', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='bottom_card_icon',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='users-round', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='bottom_card_subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='bottom_card_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='centres_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='floating_stat_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='floating_stat_value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='secondary_cta_external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='secondary_cta_internal_page',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.page'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='secondary_cta_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='top_card_icon',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='graduation-cap', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='top_card_subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='top_card_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcta',
            name='secondary_cta_external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalcta',
            name='secondary_cta_internal_page',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.page'),
        ),
        migrations.AddField(
            model_name='historicalcta',
            name='secondary_cta_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpartnerlogo',
            name='kind',
            field=models.CharField(choices=[('partner', 'Hiring Partner'), ('tool', 'Software Tool')], default='partner', help_text='Which marquee row this appears in. Each row renders with one fixed icon (not per-item).', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaltestimonial',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltestimonial',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltestimonial',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaltestimonial',
            name='video_thumbnail',
            field=models.TextField(blank=True, help_text='Used when Kind is Video.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestimonial',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Used when Kind is Video.'),
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='kind',
            field=models.CharField(choices=[('partner', 'Hiring Partner'), ('tool', 'Software Tool')], default='partner', help_text='Which marquee row this appears in. Each row renders with one fixed icon (not per-item).', max_length=10),
        ),
        migrations.AddField(
            model_name='scrollitem',
            name='icon',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='sparkles', max_length=32),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Used when Kind is Video.', null=True, upload_to='modules/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Used when Kind is Video.'),
        ),
        migrations.AlterField(
            model_name='credentialitem',
            name='icon',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='shield-check', max_length=32),
        ),
        migrations.AlterField(
            model_name='credentialitem',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalpartnerlogo',
            name='logo',
            field=models.TextField(blank=True, help_text='Optional — the current homepage marquee shows text only, no logos.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional — the current homepage marquee shows text only, no logos.', null=True, upload_to='modules/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('heading_level', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=2)),
                ('paragraph', models.TextField(blank=True, help_text='Not currently rendered on the homepage; reserved for future use.')),
                ('background_image', models.ImageField(blank=True, help_text='Not currently rendered on the homepage; reserved for future use.', null=True, upload_to='modules/%Y/%m/')),
                ('background_image_alt', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, help_text='Overrides the default "Compare all N programs..." link text.', max_length=100)),
                ('button_external_url', models.URLField(blank=True)),
                ('button_internal_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='pages.page')),
            ],
            options={
                'verbose_name': 'Course Section',
                'ordering': ['page', 'display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Matches the course detail page slug, e.g. /courses/<slug>.', max_length=255)),
                ('category', models.CharField(help_text='Finance, Taxation, Analytics, Marketing, or Gulf — matches the homepage tabs.', max_length=50)),
                ('badge', models.CharField(help_text='Visible badge text; also used as the program-type filter key (e.g. "Job Assured").', max_length=50)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(blank=True, help_text='e.g. "Online & Offline".', max_length=100)),
                ('tool', models.CharField(blank=True, help_text='Software/tools used, e.g. "Tally Prime + SAP FICO".', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, help_text='Defaults to "View Details" if blank.', max_length=100)),
                ('button_external_url', models.URLField(blank=True)),
                ('button_internal_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='modules.coursesection')),
            ],
            options={
                'verbose_name': 'Course Card',
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroAnimatedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('word', models.CharField(max_length=100)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animated_words', to='modules.banner')),
            ],
            options={
                'verbose_name': 'Hero Animated Word',
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCourseSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('heading_level', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=2)),
                ('paragraph', models.TextField(blank=True, help_text='Not currently rendered on the homepage; reserved for future use.')),
                ('background_image', models.TextField(blank=True, help_text='Not currently rendered on the homepage; reserved for future use.', max_length=100, null=True)),
                ('background_image_alt', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, help_text='Overrides the default "Compare all N programs..." link text.', max_length=100)),
                ('button_external_url', models.URLField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('button_internal_page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.page')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.page')),
            ],
            options={
                'verbose_name': 'historical Course Section',
                'verbose_name_plural': 'historical Course Sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWhyFinprovSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('heading_level', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=2)),
                ('paragraph', models.TextField(blank=True, help_text='Not currently rendered on the homepage; reserved for future use.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.page')),
            ],
            options={
                'verbose_name': 'historical Why Finprov Section',
                'verbose_name_plural': 'historical Why Finprov Sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WhyFinprovSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('heading_level', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=2)),
                ('paragraph', models.TextField(blank=True, help_text='Not currently rendered on the homepage; reserved for future use.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='pages.page')),
            ],
            options={
                'verbose_name': 'Why Finprov Section',
                'ordering': ['page', 'display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Not currently rendered on the homepage; reserved for future use.')),
                ('icon', models.CharField(blank=True, choices=[('award', 'Award'), ('map-pin', 'Map Pin'), ('graduation-cap', 'Graduation Cap'), ('users-round', 'Users'), ('badge-check', 'Badge Check'), ('shield-check', 'Shield Check'), ('star', 'Star'), ('trophy', 'Trophy'), ('check-circle', 'Check Circle'), ('sparkles', 'Sparkles'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase'), ('wrench', 'Wrench'), ('target', 'Target'), ('rocket', 'Rocket'), ('heart-handshake', 'Heart Handshake')], default='sparkles', help_text='Not currently rendered on the homepage; reserved for future use.', max_length=32)),
                ('image', models.ImageField(blank=True, help_text='Not currently rendered on the homepage; reserved for future use.', null=True, upload_to='modules/%Y/%m/')),
                ('why_finprov_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='modules.whyfinprovsection')),
            ],
            options={
                'verbose_name': 'Feature Card',
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
    ]
