# Generated by Django 5.2.16 on 2026-08-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_credentialitem_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecard',
            name='program_type',
            field=models.CharField(default='', help_text='Job Assured, Certification, or Executive — matches the homepage filter pills.', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursecard',
            name='badge',
            field=models.CharField(help_text='Visible badge text on the card (can differ from Program Type, e.g. "Flagship").', max_length=50),
        ),
    ]
