# Generated by Django 5.2.16 on 2026-08-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_coursecard_program_type_alter_coursecard_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestimonial',
            name='program',
            field=models.CharField(blank=True, default='', help_text='The course/program name shown under the student\'s name, e.g. "SAP FICO & ACCA".', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='program',
            field=models.CharField(blank=True, default='', help_text='The course/program name shown under the student\'s name, e.g. "SAP FICO & ACCA".', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Not currently rendered on the homepage; reserved for future use.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Not currently rendered on the homepage; reserved for future use.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Not currently rendered on the homepage; reserved for future use.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Not currently rendered on the homepage; reserved for future use.', max_length=255),
        ),
    ]
