# Generated by Django 5.2.16 on 2026-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_historicallifeatfinprovsection_historicalquiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Management, Faculty', max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='credentials',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience',
            field=models.CharField(blank=True, help_text='e.g. "20+ Years Practice"', max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='highlights',
            field=models.TextField(blank=True, help_text='One highlight per line.'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='quote',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
