# Generated by Django 5.2.16 on 2026-08-10 09:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_historicallegalsection_legalsection'),
        ('pages', '0003_historicalpage_wp_post_id_page_wp_post_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLandingPageBody',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('h1', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Raw HTML. Supported tags: p, ul, ol, li, strong, em, b, i, u, a, br, h2-h6. Sanitized server-side before it reaches the API.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.page')),
            ],
            options={
                'verbose_name': 'historical Landing Page Body',
                'verbose_name_plural': 'historical Landing Page Bodys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LandingPageBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('h1', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Raw HTML. Supported tags: p, ul, ol, li, strong, em, b, i, u, a, br, h2-h6. Sanitized server-side before it reaches the API.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='pages.page')),
            ],
            options={
                'verbose_name': 'Landing Page Body',
                'ordering': ['page', 'display_order'],
                'abstract': False,
            },
        ),
    ]
