# Generated by Django 5.2.16 on 2026-08-11 04:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_historicallandingpagebody_landingpagebody'),
        ('pages', '0003_historicalpage_wp_post_id_page_wp_post_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHistorySection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('heading_level', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=2)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above the heading, e.g. "Decade of Excellence".', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.page')),
            ],
            options={
                'verbose_name': 'historical History Section',
                'verbose_name_plural': 'historical History Sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('heading_level', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=2)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above the heading, e.g. "Decade of Excellence".', max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='pages.page')),
            ],
            options={
                'verbose_name': 'History Section',
                'ordering': ['page', 'display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('year_label', models.CharField(help_text='e.g. "2014 — The Foundation".', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='modules.historysection')),
            ],
            options={
                'verbose_name': 'History Milestone',
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
    ]
