# Generated by Django 5.2.16 on 2026-08-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_history_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecard',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltestimonial',
            name='video_thumbnail_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_thumbnail_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
