# Generated by Django 5.2.16 on 2026-08-11 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('modules', '0010_featurecard_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecard',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_cards', to='courses.course'),
        ),
    ]
