# Generated by Django 5.2.16 on 2026-08-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_migrate_author_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_role',
        ),
        migrations.RemoveField(
            model_name='historicalblogpost',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='historicalblogpost',
            name='author_role',
        ),
    ]
