# Generated by Django 5.2.16 on 2026-08-11 09:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('badge_css_class', models.CharField(blank=True, help_text='Imported presentation fallback; not editorial.', max_length=255)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('tool_summary', models.CharField(blank=True, max_length=500)),
                ('short_description', models.TextField(blank=True)),
                ('hero_description', models.TextField(blank=True)),
                ('snapshot_text', models.TextField(blank=True)),
                ('online_fees', models.CharField(blank=True, max_length=255)),
                ('offline_fees', models.CharField(blank=True, max_length=255)),
                ('fee_summary', models.CharField(blank=True, max_length=500)),
                ('eligibility', models.TextField(blank=True)),
                ('hours_of_learning', models.CharField(blank=True, max_length=100)),
                ('industry_projects', models.CharField(blank=True, max_length=100)),
                ('tools_used_stat', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('syllabus_pdf', models.FileField(blank=True, null=True, upload_to='courses/syllabi/%Y/%m/')),
                ('syllabus_button_text', models.CharField(blank=True, default='Download Syllabus Brochure', max_length=100)),
                ('source_payload', models.JSONField(blank=True, default=dict, editable=False)),
                ('source_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('needs_content_review', models.BooleanField(default=False)),
                ('needs_url_review', models.BooleanField(default=False)),
                ('review_notes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['display_order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Course categories',
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCareerProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_prospects', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCurriculumModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_modules', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.coursecurriculummodule')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseHiringPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_partners', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseJobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_opportunities', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.courseprogramtype'),
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='courses.course')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCourse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('badge_css_class', models.CharField(blank=True, help_text='Imported presentation fallback; not editorial.', max_length=255)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('tool_summary', models.CharField(blank=True, max_length=500)),
                ('short_description', models.TextField(blank=True)),
                ('hero_description', models.TextField(blank=True)),
                ('snapshot_text', models.TextField(blank=True)),
                ('online_fees', models.CharField(blank=True, max_length=255)),
                ('offline_fees', models.CharField(blank=True, max_length=255)),
                ('fee_summary', models.CharField(blank=True, max_length=500)),
                ('eligibility', models.TextField(blank=True)),
                ('hours_of_learning', models.CharField(blank=True, max_length=100)),
                ('industry_projects', models.CharField(blank=True, max_length=100)),
                ('tools_used_stat', models.CharField(blank=True, max_length=100)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('syllabus_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('syllabus_button_text', models.CharField(blank=True, default='Download Syllabus Brochure', max_length=100)),
                ('source_payload', models.JSONField(blank=True, default=dict, editable=False)),
                ('source_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('needs_content_review', models.BooleanField(default=False)),
                ('needs_url_review', models.BooleanField(default=False)),
                ('review_notes', models.JSONField(blank=True, default=list)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.coursecategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.courseprogramtype')),
            ],
            options={
                'verbose_name': 'historical course',
                'verbose_name_plural': 'historical courses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
