# Generated by Django 5.2.16 on 2026-08-11 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('encoding', 'Encoding issue'), ('scraped_navigation', 'Scraped navigation'), ('url', 'Canonical / slug conflict'), ('seo', 'Missing SEO metadata'), ('ownership', 'Landing-page ownership conflict')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('blocking', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('corrected', 'Corrected')], default='open', max_length=10)),
                ('resolution_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_review_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'field_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'issue_key'), name='unique_course_review_issue')],
            },
        ),
    ]
