# Generated by Django 5.2.16 on 2026-08-04 09:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=255, unique=True)),
                ('new_path', models.CharField(max_length=255)),
                ('redirect_type', models.PositiveSmallIntegerField(choices=[(301, '301 (Permanent)'), (302, '302 (Temporary)')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSEOMeta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('focus_keyword', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('meta_robots', models.CharField(choices=[('index,follow', 'Index, Follow'), ('noindex,follow', 'Noindex, Follow'), ('index,nofollow', 'Index, Nofollow'), ('noindex,nofollow', 'Noindex, Nofollow')], default='index,follow', max_length=20)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.TextField(blank=True, max_length=100, null=True)),
                ('og_url', models.URLField(blank=True)),
                ('schema_type', models.CharField(choices=[('none', 'None'), ('organization', 'Organization'), ('article', 'Article'), ('faq', 'FAQ'), ('course', 'Course'), ('breadcrumb', 'Breadcrumb'), ('localbusiness', 'LocalBusiness'), ('product', 'Product')], default='none', max_length=20)),
                ('custom_schema_json', models.JSONField(blank=True, help_text='Optional raw JSON-LD override.', null=True)),
                ('include_in_sitemap', models.BooleanField(default=True)),
                ('author_name', models.CharField(blank=True, help_text='Blog pages only.', max_length=255)),
                ('author_bio', models.TextField(blank=True)),
                ('author_image', models.TextField(blank=True, max_length=100, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.page')),
            ],
            options={
                'verbose_name': 'historical SEO Meta',
                'verbose_name_plural': 'historical SEO Meta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('focus_keyword', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('meta_robots', models.CharField(choices=[('index,follow', 'Index, Follow'), ('noindex,follow', 'Noindex, Follow'), ('index,nofollow', 'Index, Nofollow'), ('noindex,nofollow', 'Noindex, Nofollow')], default='index,follow', max_length=20)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/%Y/%m/')),
                ('og_url', models.URLField(blank=True)),
                ('schema_type', models.CharField(choices=[('none', 'None'), ('organization', 'Organization'), ('article', 'Article'), ('faq', 'FAQ'), ('course', 'Course'), ('breadcrumb', 'Breadcrumb'), ('localbusiness', 'LocalBusiness'), ('product', 'Product')], default='none', max_length=20)),
                ('custom_schema_json', models.JSONField(blank=True, help_text='Optional raw JSON-LD override.', null=True)),
                ('include_in_sitemap', models.BooleanField(default=True)),
                ('author_name', models.CharField(blank=True, help_text='Blog pages only.', max_length=255)),
                ('author_bio', models.TextField(blank=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='seo/%Y/%m/')),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='pages.page')),
            ],
            options={
                'verbose_name': 'SEO Meta',
                'verbose_name_plural': 'SEO Meta',
            },
        ),
    ]
