# Generated by Django 5.2.16 on 2026-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseometa',
            name='focus_keyword',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalseometa',
            name='schema_type',
            field=models.CharField(choices=[('none', 'None'), ('webpage', 'WebPage'), ('organization', 'Organization'), ('article', 'Article'), ('blogposting', 'BlogPosting'), ('faq', 'FAQ'), ('course', 'Course'), ('breadcrumb', 'Breadcrumb'), ('localbusiness', 'LocalBusiness'), ('product', 'Product')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='focus_keyword',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='schema_type',
            field=models.CharField(choices=[('none', 'None'), ('webpage', 'WebPage'), ('organization', 'Organization'), ('article', 'Article'), ('blogposting', 'BlogPosting'), ('faq', 'FAQ'), ('course', 'Course'), ('breadcrumb', 'Breadcrumb'), ('localbusiness', 'LocalBusiness'), ('product', 'Product')], default='none', max_length=20),
        ),
    ]
