# Generated by Django 5.2.16 on 2026-08-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('pages', '0002_seed_page_types'),
        ('seo', '0002_alter_historicalseometa_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseometa',
            name='blog_post',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='blog_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='pages.page'),
        ),
    ]
