# Generated by Django 5.2.16 on 2026-08-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_historicalseometa_blog_post_seometa_blog_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseometa',
            name='og_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seometa',
            name='og_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
