# Generated by Django 5.2.16 on 2026-08-11 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('seo', '0004_historicalseometa_og_image_alt_seometa_og_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseometa',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.course'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='courses.course'),
        ),
    ]
