# Generated by Django 5.2.16 on 2026-08-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Finprov', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('custom_404_title', models.CharField(blank=True, default='Page not found', max_length=255)),
                ('custom_404_message', models.TextField(blank=True)),
                ('custom_404_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
